<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Vell</AssemblyName>
    <RootNamespace>Vell</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon Condition="Exists('icone.ico')">icone.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Authors>bovmii</Authors>
    <Copyright>Copyright © 2026 @bovmii. PolyForm Noncommercial 1.0.0. Resale prohibited.</Copyright>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="icone.png" />
  </ItemGroup>
</Project>
